### ISSUE TITLE
Question: What is the purpose of having 2 dataset variables in the web/.env file?

### ISSUE THREAD

**Issue by nboliver** [jetskis/midway#11]
web/.env has `SANITY_DATASET` and `GATSBY_SANITY_PROJECTSET`. 
Is there a specific reason to have 2 variables that store the dataset?

**Comment by iamkevingreen** [comment]
`GATSBY_` variables are accessible in the client, it's to prevent you from unknowingly exposing values that you'd like to otherwise keep private. And to keep the client-side vs server-side env variables separate, you can obviously change it to however you'd like though :).
