### ISSUE TITLE
Suggestion: Community development discord channel

### ISSUE THREAD

**Issue by Jore** [jetskis/midway#13]
It would be good to be able to talk to each other around the development of this project

**Comment by iamkevingreen** [comment]
I'm not very hip to the discord life, I wouldn't mind it, but not sure how active I would be in the community. I do actually want to ask those using this a few questions about the roadmap so maybe I'll set something up.

**Comment by iamkevingreen** [comment]
@Jore I have applied for the Github Beta Discussions, hoping I get approved shortly and we can move some real discussions there.

**Comment by Jore** [comment]
Fantastic. Thanks so much.
