### ISSUE TITLE
Unable Promote Shopify Products to Sanity.

### ISSUE THREAD

**Issue by willTastyMakers** [jetskis/midway#16]
H @iamkevingreen  and others who have and are still participating in developing this product,

I am very keen to get this work flow enabled between  Shopify, Gatsby, Sanity, and Netlify. I have been working the repo, and following the  "Getting Started Guide", but I am not able to get any of my Shopify products to appear in Sanity. 

-  Set up Sanity Dashboard correctly after updating to the latest 2.0.*  [( I had an issue get sanity to build which I logged here, and then closed, after updating sanity packages with latest releases enabling it to correctly build.)](https://github.com/ctrl-alt-del-world/midway/issues/14) .  

- Set up Netlify correctly with pipeline deploying and  **Publishing**  when I push to github repo master branch.

- My version of the midway site appears in Netlify [ hungry-dubinsky-4c5dfe.netlify.app](https://hungry-dubinsky-4c5dfe.netlify.app/)

- Created a Shopify dev store, using Oberlo imported 20 or so products ( with lots of images), created collections, made all the products active and  finally created webhooks for Product  **create, update, and delete**  also made sure each of the t **Webhook API version**   in the hook creator was set to **2020-07**
    hook url for each set to:   https://hungry-dubinsky-4c5dfe.netlify.com/.netlify/functions/shopify-sync
     
- Locally  ran   ```npm run dev``` script  to get netlify dev going with ngrok. ( I have ngrok installed on my machine... having used in previously for some other work with Shopify App development)

- Changed the description and title of products... saving each time in hopes of seeing some signs of life, but ......  Nada Nunca...  none of the Shopify products ever appear with in the Dashboard and I don't see any console log statements in my terminal or in the netlify functions logger...

**Debugging Attempts**:

--  Tried sending  test notifications for each hook, while my ../sites/hungry-dubinsky-4c5dfe/functions/shopify-sync  function log is open but don't see anything registering. ( In fact terminal seems in permanent stasis as the spinning pipe "|" is the only thing that shows. I also went into the sites/settings/functions'  tab and inserted  'functions/'  for Functions Directory: )

![Screen Shot 2020-10-28 at 2 17 25 PM](https://user-images.githubusercontent.com/58872627/97497885-73602880-1928-11eb-9179-077d381c54b9.png)

 **( 2 hours after posting this isssue here)**   I am inconsistently getting something in the '../sites/hungry-dubinsky-4c5dfe/functions/shopify-sync'
        -  When I directly place https://hungry-dubinsky-4c5dfe.netlify.app/.netlify/functions/shopify-sync in the browser, 7 out of 10 times,  I get  an event in the netlify ../functions/shopify-sync... Trying the same thing from the web-hooks Test Notification  in Shopify, and I manage to get same type of notification but with much less frequency... perhaps 2 out of the 10 times I try

![Screen Shot 2020-10-28 at 2 13 30 PM](https://user-images.githubusercontent.com/58872627/97497494-cd142300-1927-11eb-9671-12983535fc17.png)

-- Added a console log statement  in shopify-sync.ts on line 197
```
try {
      return client.fetch(`*[_type == "product" && _id == "${data.id.toString()}"][0] {
        ...,
        content {
          ...,
          shopify {
            ...,
            variants[]->
          }
        }
      }`)
        .then(res => {
         console.log('lambada/shopify-sync.ts  res =', res);
```

-- I also have not been able to see any data updates from shopify happening through ngrok... which I loaded and ran in a separate terminal.

I know everyone who is working on this is super busy and saw the note about addressing issues when you can get to release version 1.0.0,  so I don't mean to be a nuisance, but if you could give me any clues as to how I might continue debugging this  on my way to setting this up and participating in the fun, I'd be super appreciative and definitely honored to help contribute in the development efforts in what every way  would be most beneficial.

My repo: [https://github.com/willTastyMakers/tasty-midway-sanity](https://github.com/willTastyMakers/tasty-midway-sanity)

Thanks...

**Comment by iamkevingreen** [comment]
@willTastyMakers This is very thorough and making debugging it actually more difficult then I thought it would. I feel like the issue might actually be with the Sanity hook/check. I've actually rewritten the sanity-sync again to not hit sanity first and instead hit Shopify. 

I'd be happy to poke around if you're comfortable/project is young enough. If you don't mind inviting me to the netlify/shopify instance I can try and get the sync working and report back what i find, I have accounts in both under my email: kevin@ctrlaltdel.world 

As for a 1.0, I am rewriting a lot of the sync stuff and probably abstracting it into a shopify app, I am currently using midway on three more projects though so I know it's totally operational just not sure what part is missing here. The repo will most likely continue to be a kitchen sink of all these ideas until early 2021 when I focus some more efforts on it.

**Comment by willTastyMakers** [comment]
@iamkevingreen 
Mad appreciation. Hopefully, you have received invites from both Sanity and Netlify.  In your current projects have you had to updating your sanity npm libs  from '1.*' to '2.*'? Before I could even get the studio app to compile locally with the sanity tabs package, I had to update to 2. I wonder if it is one of those updates that might not be effected with established implementations, but changed for newer ones. Perhaps, these issues only arise, when building a new  flow... 

I can't call it though...I don't know,  I'ma NooB to Sanity and Netlify...   I

**Comment by iamkevingreen** [comment]
@willTastyMakers the only I probably need the most is actually the Shopify* specifically i imagine it's probably in there. And I do need to update sanity + tabs I'll do that in the studio now.

**Comment by DanielHirunrusme** [comment]
@iamkevingreen Hey there, also another fan here of the starter. I've tested this in the past working fine. I tried again with a fresh install, but stuck with the product sync as well. I'm getting the below error message in Netlify. Triple checked all my env variables, webhooks, etc.

Perhaps this is related to @willTastyMakers issue? 

Will let you two know if I find a solution to see if it helps.

`5:34:13 PM: 2020-10-30T21:34:13.394Z	ce1a1fa3-edd2-4832-a116-d62f412d6b36	INFO	Successfully updated/patched Product 4796384870454 in Sanity
5:34:13 PM: 2020-10-30T21:34:13.940Z	ce1a1fa3-edd2-4832-a116-d62f412d6b36	INFO	i: The mutation(s) failed: mutation failed on document "perm-check-VRhlczcD44JAF73s": Insufficient permissions; permission "create" required    at onResponse (/var/task/src/functions/shopify-sync.js:6:83185)    at /var/task/src/functions/shopify-sync.js:6:85339    at /var/task/src/functions/shopify-sync.js:6:84168    at /var/task/src/functions/shopify-sync.js:6:84276    at O (/var/task/src/functions/shopify-sync.js:6:87414)    at /var/task/src/functions/shopify-sync.js:6:88927    at s.<anonymous> (/var/task/src/functions/shopify-sync.js:8:100)    at Object.onceWrapper (events.js:421:28)    at s.emit (events.js:327:22)    at P (/var/task/src/functions/shopify-sync.js:6:34096) {  response: {    body: { error: [Object] },    url: 'https://hy21angs.api.sanity.io/v1/assets/images/production',    method: 'POST',    headers: {      'content-type': 'application/json; charset=utf-8',      'content-length': '357',      'x-served-by': 'panna-cotta-69cc6ff89f-pkrkn',      etag: 'W/"165-tWOjvPb5t/VlZMtP0Qh7qCnwKFI"',      date: 'Fri, 30 Oct 2020 21:34:13 GMT',      vary: 'Origin',      via: '1.1 google',      'alt-svc': 'clear',      connection: 'close'    },    statusCode: 403,    statusMessage: 'Forbidden'  },  statusCode: 403,  responseBody: '{\n' +    '  "error": {\n' +    '    "description": "The mutation(s) failed: mutation failed on document \\"perm-check-VRhlczcD44JAF73s\\": Insufficient permissions; permission \\"create\\" required",\n' +    '    "items": [\n' +    '      {\n' +    '        "error": {\n' +    '          "description": "Insufficient permissions; permission \\"create\\" required",\n' +    '          "permission": "create",\n' +    '          "type": "insufficientPermissionsError"\n' +    '        },\n' +    '        "index": 0\n' +    '      }\n' +    '    ],\n' +    '    "type": "mutationError"\n' +    '  }\n' +    '}',  details: {    description: 'The mutation(s) failed: mutation failed on document "perm-check-VRhlczcD44JAF73s": Insufficient permissions; permission "create" required',    items: [ [Object] ],    type: 'mutationError'  }}
5:34:13 PM: 2020-10-30T21:34:13.940Z	ce1a1fa3-edd2-4832-a116-d62f412d6b36	INFO	Updating/patching Variants 32934243401782, 32934243434550, 32934243467318, 32934243500086 in Sanity
5:34:13 PM: 2020-10-30T21:34:13.940Z	ce1a1fa3-edd2-4832-a116-d62f412d6b36	INFO	Adding variant references to 4796384870454 in Sanity
5:34:14 PM: 2020-10-30T21:34:14.063Z	ce1a1fa3-edd2-4832-a116-d62f412d6b36	INFO	this is an error i: The mutation(s) failed: mutation failed on document "4796384870454": Insufficient permissions; permission "create" required    at onResponse (/var/task/src/functions/shopify-sync.js:6:83185)    at /var/task/src/functions/shopify-sync.js:6:85339    at /var/task/src/functions/shopify-sync.js:6:84168    at /var/task/src/functions/shopify-sync.js:6:84276    at O (/var/task/src/functions/shopify-sync.js:6:87414)    at /var/task/src/functions/shopify-sync.js:6:88927    at s.<anonymous> (/var/task/src/functions/shopify-sync.js:8:100)    at Object.onceWrapper (events.js:421:28)    at s.emit (events.js:327:22)    at P (/var/task/src/functions/shopify-sync.js:6:34096) {  response: {    body: { error: [Object] },    url: 'https://hy21angs.api.sanity.io/v1/data/mutate/production?returnIds=true&visibility=sync',    method: 'POST',    headers: {      'content-type': 'application/json; charset=utf-8',      'content-length': '344',      'x-sanity-shard': 'gcp-eu-w1-01-prod-1013',      'x-served-by': 'gradient-web-6d84c4697b-gdsss',      date: 'Fri, 30 Oct 2020 21:34:14 GMT',      vary: 'Origin',      xkey: 'project-hy21angs, project-hy21angs-production',      via: '1.1 google',      'alt-svc': 'clear',      connection: 'close'    },    statusCode: 403,    statusMessage: 'Forbidden'  },  statusCode: 403,  responseBody: '{\n' +    '  "error": {\n' +    '    "description": "The mutation(s) failed: mutation failed on document \\"4796384870454\\": Insufficient permissions; permission \\"create\\" required",\n' +    '    "items": [\n' +    '      {\n' +    '        "error": {\n' +    '          "description": "Insufficient permissions; permission \\"create\\" required",\n' +    '          "permission": "create",\n' +    '          "type": "insufficientPermissionsError"\n' +    '        },\n' +    '        "index": 0\n' +    '      }\n' +    '    ],\n' +    '    "type": "mutationError"\n' +    '  }\n' +    '}',  details: {    description: 'The mutation(s) failed: mutation failed on document "4796384870454": Insufficient permissions; permission "create" required',    items: [ [Object] ],    type: 'mutationError'  }}
5:34:14 PM: Duration: 858.27 ms	Memory Usage: 73 MB	Init Duration: 278.77 ms	`

**Comment by willTastyMakers** [comment]
Hi @DanielHirunrusme,

Thanks and I if I find a solution I will post it here as well. Are you able to get your local Gatsby to receive function invocations to  your lamda/functions/shopify-sync from Shopify?  Also, if don't mind can you tell me where the log out put you posted is from?

**Comment by willTastyMakers** [comment]
@iamkevingreen  & @DanielHirunrusme,

After getting ngrok working with a reserve domain  and using that reserve domain with a shopify notification hook, I was able to get products  I've  update on shopify to surface with in my sanity domain.  I believe my issues was happening because of the url I was using in the  in my Shopify Notification Hook...     
I was using  **.com**  as in
```https://hungry-dubinsky-4c5dfe.netlify.com/.netlify/functions/shopify-sync```
instead of **.app**
```https://hungry-dubinsky-4c5dfe.netlify.app/.netlify/functions/shopify-sync```

Once I got that action working, update products were arriving in my sanity domain.

However, I am facing a new issue, which I think may be related to @DanielHirunrusme.

My Netlify deploy is failing when building  the static product view pages of  those products now in sanity. 

![Screen Shot 2020-10-30 at 6 42 08 PM](https://user-images.githubusercontent.com/58872627/97768359-b31d4080-1adf-11eb-82cd-ed2d3241a052.png)

Without actually reviewing the code that is used to build that static product page, I am guessing I can check for the existence of assets, the before the **mainImage.assets._id** is called. However, I think there may be some issue with the translation of the shopify product properties. I will try to look more into this weekend.

**Comment by iamkevingreen** [comment]
@willTastyMakers your new error appears to be a simple `didn't upload an image` type of situation. I don't have explicit enough checks for some things like images, but images are also mostly required throughout the sanity schema. If you upload an image you shouldn't run into that issue. 

And yes the image sync is a bit glitchy right now which I don't really understand because I did get it working and now it's not.. 

If you have the products actually going into Shopify now though! and i didn't even notice the .app thing so we both missed it. then please close those and we can start a new thread for the image, but I'll most likely take a look at the image sync monday, as well as upload the new sanity-sync I've been working through to better handle not polling sanity unnecessarily. 

Cheers
