### ISSUE TITLE
Shopify products sync, but always appear out of stock

### ISSUE THREAD

**Issue by Half-stuff** [jetskis/midway#23]
Hi @iamkevingreen, 
Thank you for all of the work you've put into this. I am a novice here so I apologize if this is just an oversight on my end. 

I am able to successfully sync products from shopify, but the product pages always show 'Get notifed when stock is replenished' and the product cards also don't show the 'quick add' options. My shopify products have inventory and this problem persists even when 'Continue selling when out of stock' is enabled on shopify. 
If this sounds like a quick fix you could assist with or if you could point me in the direction of where to troubleshoot, i would greatly appreciate it.
Thanks!

**Comment by iamkevingreen** [comment]
@Half-stuff my guess is the product is not available on the storefront sales channel you've created. In the top right of your product (in shopify) ensure that the name of the storefront app you made is checked off. Just because a product is showing up on the frontend doesn't mean it can be purchased with the buy-sdk unless it's enabled there. (takes a second to refresh too)

**Comment by Half-stuff** [comment]
Hi! Just a disclaimer, please treat me like a complete idiot because i don't know what i'm doing. With that in mind, I feel bad wasting your time with this, so if the answer isn't clear or sounds like it would take too much time, just say so and I will close this issue and wait for future updates.

I checked and the products are set to active and it shows that the Storefront (listed as Sanity) app is checked off. 
<img width="200" alt="Screen Shot 2021-01-13 at 11 20 57 AM" src="https://user-images.githubusercontent.com/43104258/104499095-6c44d000-5591-11eb-8635-3794bb710828.png">
In the shopify online store, I'm able to add items to cart and go to checkout, which leads me to believe the products are setup correctly in shopify.
I ran ngrok and was able to find that the products have "inventory_quantity" listed, but I'm not sure if there is a different line i should be checking for there?

Things that might be relevant?:
It seems like 'available' might have something to do with the waitlist being displayed (?) and i get this error upon building "warn Error: [98, 47]: Shadowed name: 'available'"
I'm also seeing some issues in my form.tsx
<img width="791" alt="Screen Shot 2021-01-13 at 11 39 58 AM" src="https://user-images.githubusercontent.com/43104258/104501123-26d5d200-5594-11eb-8eed-027bf6ea7cdf.png">

<img width="925" alt="Screen Shot 2021-01-13 at 11 37 08 AM" src="https://user-images.githubusercontent.com/43104258/104500770-ae6f1100-5593-11eb-99b1-fc427904aff7.png">

Thanks!

**Comment by iamkevingreen** [comment]
The linter errors are just TS related, shouldn't actually have any bearing on the issues here. Assuming you've double checked all permissions on your storefront api to have access to the products etc?

Does look like you have the sales channels set up correctly, it's sort of hard to say without knowing the whole picture here, I feel like i've encountered this issue multiple times but not sure what step in the process you are at unfortunately. Let me know if you can provide any additional information here.

**Comment by Half-stuff** [comment]
Yeah, I believe i had the permissions are set up correctly. All the storefront API options are enabled. I added read access to all of the admin api permissions just to check, but that didn't change anything. I also set up a different trial shopify account (not a development store) and ran into the same issue after updating everything, but if the error is in my shopify setup then i just replicated the error. I also set up the bogus payment portal, but that changed nothing.

I am clearly in over my head here and unsure of what information is relevant, sorry. 
<img width="400" alt="Screen Shot 2021-01-13 at 6 23 08 PM" src="https://user-images.githubusercontent.com/43104258/104536415-eb0b2e80-55cc-11eb-8ee4-2d8aa7e85323.png">
Based on this, I turned off inventory tracking for the products, but the problem persisted, so even if products are seen as 'available', they still aren't showing the purchase options?

In a web browser, https://key:password@url/admin/api/2020-10/locations.json returns the expected data, so i have my info typed correctly, but /admin/api/2020-10/graphql.json puts out {"errors":"Not Found"}. From what i can find online, not reaching graphql.json might be normal (im possibly sending GET instead of POST?), but the first part is validation that my API credentials are correct

Do you think this is an API issue? Any suggestions of what to look for? If not, I'l assume its user error and keep checking, but I'll stop posting irrelevant findings here until I solve it.

**Comment by iamkevingreen** [comment]
The only thing you should be interacting with on the product level is the buy-sdk, no admin api interaction is necessary, if you're in the Sanity slack you can feel free to DM me with more information...

I feel like it's something simple, but it's usually just adding stock and that's about all it usually takes if it's enabled on the right sales channels. If you really want to troubleshoot minus the whole experience, I would just do a buy-sdk fetch on products and check that availability there as well: https://shopify.github.io/js-buy-sdk/#fetching-products You can interact with it via the context anywhere by importing the client or just do it in the siteContext file directly for testing to see if things are looking correctly there.

**Comment by iamkevingreen** [comment]
We resolved this offline, the env variable was incorrect for the buy-sdk. (I've updated the env variable and will make note of a few of the instructions that were harder to follow)
