### ISSUE TITLE
Shopify products not syncing

### ISSUE THREAD

**Issue by accaplan** [jetskis/midway#5]
Hi, thank you for this template!

A little above my competency levels to say the least. Unfortunately after following the steps my products wont sync from shopify.
Any idea where the problem might be?

I realize that is vague but I have the env variables set with sanity and shopify tokens, the app created in shopify, web hooks in shopify and functions in netlify. Do i have to set any webhooks in sanity?

lambda functions are running in netlify...

**Comment by iamkevingreen** [comment]
@accaplan I'd recommend some console logging, and if you can run ngrok locally run the webhooks directly to your local so you can troubleshoot it faster. I can't remember if password protection blocks webhooks, in case you have a password on the shopify site, that could also be it!

**Comment by accaplan** [comment]
I will be gosh darned! Thanks you for the response... Indeed it was as simple as removing the password on the shopify site. Best to you and look forward to future developments.
